# Base config to generate config dir
# Last updated: 2023-04-27 14:51:04.530019

# The param is where to store the generated config files, 
# base path is /home/cls2021/cvkdnk/workspace/PolarFusion/experiments
Dirname: SegMapGS

# [SemanticKITTI] [NuScenes]
Dataset: SemanticKITTI

# [PointAugmentor] [InsAugPointAugmentor] [Cylindrical] [RangeProject] [BevProject]
# [PolarBevProject]
DataPipeline:
    base:
    - Cylindrical
    - RangeProject

    train:
    - PointAugmentor  # cover the base pipeline

# [Cylinder3DSPConv] [Cy3D_SegMap_GS]
Model: Cy3D_SegMap_GS

# [VoxelWCE] [VoxelLovasz] [VoxelWCELovasz] [MultiLogitsLoss]
Loss: MultiLogitsLoss

# [Adam] [SGD]
Optimizer: Adam

# Complete the file and run [python process_config.py -g]

