# Base config to generate config dir
# Last updated: 2023-03-23 22:48:56.673983

# The param is where to store the generated config files, 
# base path is /home/cls2021/cvkdnk/workspace/PolarFusion/experiments
Dirname: fix_iou 

# [SemanticKITTI] [NuScenes]
Dataset: SemanticKITTI

# [PointAugmentor] [InsAugPointAugmentor] [Cylindrical] [RangeProject] [BevProject]
# [PolarBevProject]
DataPipeline:
    base:
    - Cylindrical
    - RangeProject

    train:
    - PointAugmentor  # cover the base pipeline

# [Cylinder3DSPConv]
Model: Cylinder3DSPConv

# [VoxelWCE] [VoxelLovasz] [VoxelWCELovasz]
Loss: VoxelWCELovasz

# [Adam] [SGD]
Optimizer: Adam

# Complete the file and run [python process_config.py -g]

