# The param is where to store the generated config files, 
# base path is /home/neu-wang/cvkdnk/workspace/PolarFusion/experiments
Dirname: cylinder3d

# [SemanticKITTI] [NuScenes]
Dataset: SemanticKITTI

# [PointAugmentor] [InsAugPointAugmentor] [Voxel] [Cylindrical] [RangeProject]
# [BevProject] [PolarBevProject]
DataPipeline:
    train:
    - PointAugmentor
    - Cylindrical

    val:
    - Cylindrical

    test:
    - Cylindrical

# [Cylinder3D]
Model: Cylinder3D

# [CrossEntropyLoss] [LovaszSoftmax]
Loss:
- CrossEntropyLoss

# [Adam] [SGD]
Optimizer: Adam

# Complete the file and run [python process_config.py -g]

