# Base config to generate config dir
# Last updated: 2023-03-07 15:33:26.149404

# The param is where to store the generated config files, 
# base path is /home/cls2021/cvkdnk/workspace/PolarFusion/experiments
Dirname: cylinder3d

# [SemanticKITTI] [NuScenes]
Dataset: SemanticKITTI

# [PointAugmentor] [InsAugPointAugmentor] [VoxelTS] [Cylindrical] [RangeProject]
# [BevProject] [PolarBevProject]
DataPipeline:
    train:
    - PointAugmentor
    - Cylindrical
    - RangeProject

    val:
    - Cylindrical
    - RangeProject

    test:
    - Cylindrical
    - RangeProject

# [Cylinder3DTS]
Model: Cylinder3DTS

# [CrossEntropyLoss] [LovaszSoftmax]
Loss:
- CrossEntropyLoss
- LovaszSoftmax

# [Adam] [SGD]
Optimizer: Adam

# Complete the file and run [python process_config.py -g]

