# Base config to generate config dir
# Last updated: 2022-11-10 15:47:22.878934

# The param is where to store the generated config files, 
# base path is /home/neu-wang/cvkdnk/workspace/PolarFusion/config
Dirname: test

# [SemanticKITTI] [NuScenes]
Dataset: SemanticKITTI

# [PointAugmentor] [InsAugPointAugmentor] [Voxel] [Cylindrical] [RangeProject]
# [BevProject] [PolarBevProject]
DataPipeline:
    train:
    - PointAugmentor
    - Cylindrical
    - RangeProject

    val:
    - Cylindrical
    - RangeProject

    test:
    - Cylindrical
    - RangeProject

# [Cylinder3D]
Model: Cylinder3D

# [CrossEntropyLoss] [LovaszSoftmax]
Loss:
- CrossEntropyLoss
- LovaszSoftmax

# [Adam] [SGD]
Optimizer: Adam

# Complete the file and run [python process_config.py -g]